### ISSUE TITLE
can your fork also do .tar.gz and .deb files without unarchiving them ? - wishlist 

### ISSUE THREAD

**Issue by shirishag75** [wisc/sloccount#1]
This is more of a wishlist. See http://stackoverflow.com/questions/41965006/how-to-use-sloccount-with-a-tar-gz-or-deb-without-decompressing-them

I dunno if it's possible or not, but if it's possible, would you do it ?

**Comment by koffiebaard** [comment]
Hi Shirish,

It's not possible to use sloccount /without/ decompressing, but you could decompress, run the tool and remove the decompressed folder, right?

something like:
```bash
tar -xzf some_project.tar.gz && sloccount some_project; rm -rf ./some_project
```

Unfortunately i don't have time to build it into sloccount at the moment.
